export { default as ExternalLinkIcon } from './ExternalLinkIcon'
export { default as GithubIcon } from './GithubIcon'
export { default as HeartIcon } from './HeartIcon'
export { default as ReactIcon } from './ReactIcon'
export { default as TailwindIcon } from './TailwindIcon'
export { default as TriangleIcon } from './TriangleIcon'
