---
label: Project
hide_body: false
display_field: name
fields:
- name: title
  type: text
  config:
    required: true
  label: Title
- name: excerpt
  type: textarea
  default: ''
  config:
    required: true
    wysiwyg: false
    schema:
      format: markdown
  label: Excerpt
- name: tech_used
  type: tag_list
  default: []
  label: Tech used
- name: screenshot
  type: file
  config:
    maxSize: 64
  label: Screenshot
- name: links
  type: blocks
  label: Links
  template_types:
  - link
  config:
    min: 
    max: 
- name: gradient
  type: text
  config:
    required: false
  label: Gradient
pages:
- content/projects/freecodecamp-bot.md
- content/projects/natours.md
- content/projects/sheepish-io.md
