---
label: Project
hide_body: false
display_field: name
fields:
- name: title
  type: text
  config:
    required: true
  label: Title
- name: excerpt
  type: textarea
  default: ''
  config:
    required: true
    wysiwyg: false
    schema:
      format: markdown
  label: Excerpt
- name: emoji
  type: text
  config:
    required: true
  label: Emoji
- name: tags
  type: tag_list
  default: []
  label: Tags
- name: links
  type: blocks
  label: Links
  template_types:
  - link
  config:
    min: 
    max: 
- name: gradient
  type: text
  config:
    required: false
  label: Gradient
pages:
- content/projects/freecodecamp-bot.md
- content/projects/sheepish-io.md
